name: Bug report 2
description: Report a detected problem.
title: "[Bug] "
type: Bug
assignees:
  - svprdga

body:
  - type: textarea
    id: description
    attributes:
      label: Description of the problem
      placeholder: A brief, clear summary of the issue.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected result
      placeholder: What should have happened after executing the steps above.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual result
      placeholder: What actually happened instead.
    validations:
      required: true

  - type: checkboxes
    id: subtasks
    attributes:
      label: Subtasks
      options:
        - label: Subtask 1
